CREATE TABLE tt_content (
    tx_swiper_content_parent int(11) unsigned DEFAULT '0' NOT NULL,
    tx_swiper_allowslidenext int(11) DEFAULT '0' NOT NULL,
    tx_swiper_allowslideprev int(11) DEFAULT '0' NOT NULL,
    tx_swiper_allowtouchmove int(11) DEFAULT '0' NOT NULL,
    tx_swiper_autoheight int(11) DEFAULT '0' NOT NULL,
    tx_swiper_centeredslides int(11) DEFAULT '0' NOT NULL,
    tx_swiper_direction tinytext,
    tx_swiper_effect tinytext,
    tx_swiper_followfinger int(11) DEFAULT '0' NOT NULL,
    tx_swiper_freemode int(11) DEFAULT '0' NOT NULL,
    tx_swiper_freemodeminimumvelocity double(11,2) DEFAULT '0.00' NOT NULL,
    tx_swiper_freemodemomentum int(11) DEFAULT '0' NOT NULL,
    tx_swiper_freemodemomentumbounce int(11) DEFAULT '0' NOT NULL,
    tx_swiper_freemodemomentumbounceratio tinytext,
    tx_swiper_freemodemomentumratio tinytext,
    tx_swiper_freemodemomentumvelocityratio tinytext,
    tx_swiper_freemodesticky int(11) DEFAULT '0' NOT NULL,
    tx_swiper_grabcursor int(11) DEFAULT '0' NOT NULL,
    tx_swiper_height tinytext,
    tx_swiper_initialslide tinytext,
    tx_swiper_iosedgeswipedetection int(11) DEFAULT '0' NOT NULL,
    tx_swiper_iosedgeswipethreshold tinytext,
    tx_swiper_longswipes int(11) DEFAULT '0' NOT NULL,
    tx_swiper_longswipesms tinytext,
    tx_swiper_longswipesratio double(11,2) DEFAULT '0.00' NOT NULL,
    tx_swiper_loop int(11) DEFAULT '0' NOT NULL,
    tx_swiper_loopadditionalslides tinytext,
    tx_swiper_loopedslides tinytext,
    tx_swiper_loopfillgroupwithblank int(11) DEFAULT '0' NOT NULL,
    tx_swiper_nested int(11) DEFAULT '0' NOT NULL,
    tx_swiper_normalizeslideindex int(11) DEFAULT '0' NOT NULL,
    tx_swiper_noswiping int(11) DEFAULT '0' NOT NULL,
    tx_swiper_passivelisteners int(11) DEFAULT '0' NOT NULL,
    tx_swiper_preloadimages int(11) DEFAULT '0' NOT NULL,
    tx_swiper_preventclicks int(11) DEFAULT '0' NOT NULL,
    tx_swiper_preventclickspropagation int(11) DEFAULT '0' NOT NULL,
    tx_swiper_resistance int(11) DEFAULT '0' NOT NULL,
    tx_swiper_resistanceratio double(11,2) DEFAULT '0.00' NOT NULL,
    tx_swiper_roundlengths int(11) DEFAULT '0' NOT NULL,
    tx_swiper_runcallbacksoninit int(11) DEFAULT '0' NOT NULL,
    tx_swiper_setwrappersize int(11) DEFAULT '0' NOT NULL,
    tx_swiper_shortswipes int(11) DEFAULT '0' NOT NULL,
    tx_swiper_simulatetouch int(11) DEFAULT '0' NOT NULL,
    tx_swiper_slide int(11) unsigned DEFAULT '0' NOT NULL,
    tx_swiper_slidesoffsetafter tinytext,
    tx_swiper_slidesoffsetbefore tinytext,
    tx_swiper_slidespercolumn tinytext,
    tx_swiper_slidespercolumnfill tinytext,
    tx_swiper_slidespergroup tinytext,
    tx_swiper_slidesperview tinytext,
    tx_swiper_slidesperviewauto int(11) DEFAULT '0' NOT NULL,
    tx_swiper_slidetoclickedslide int(11) DEFAULT '0' NOT NULL,
    tx_swiper_spacebetween tinytext,
    tx_swiper_speed tinytext,
    tx_swiper_threshold tinytext,
    tx_swiper_touchangle tinytext,
    tx_swiper_toucheventstarget tinytext,
    tx_swiper_touchmovestoppropagation int(11) DEFAULT '0' NOT NULL,
    tx_swiper_touchratio tinytext,
    tx_swiper_touchreleaseonedges int(11) DEFAULT '0' NOT NULL,
    tx_swiper_uniquenavelements int(11) DEFAULT '0' NOT NULL,
    tx_swiper_updateonimagesready int(11) DEFAULT '0' NOT NULL,
    tx_swiper_virtualtranslate int(11) DEFAULT '0' NOT NULL,
    tx_swiper_watchslidesprogress int(11) DEFAULT '0' NOT NULL,
    tx_swiper_watchslidesvisibility int(11) DEFAULT '0' NOT NULL,
    tx_swiper_width tinytext
);
CREATE TABLE tx_swiper_slide (
    uid int(11) NOT NULL auto_increment,
    pid int(11) DEFAULT '0' NOT NULL,
    parentid int(11) DEFAULT '0' NOT NULL,
    parenttable varchar(255) DEFAULT '' NOT NULL,
    sorting int(11) unsigned DEFAULT '0' NOT NULL,
    t3ver_oid int(11) unsigned DEFAULT '0' NOT NULL,
    t3ver_id int(11) DEFAULT '0' NOT NULL,
    t3ver_wsid int(11) DEFAULT '0' NOT NULL,
    t3ver_label varchar(255) DEFAULT '' NOT NULL,
    t3ver_state tinyint(4) DEFAULT '0' NOT NULL,
    t3ver_stage int(11) DEFAULT '0' NOT NULL,
    t3ver_count int(11) DEFAULT '0' NOT NULL,
    t3ver_tstamp int(11) DEFAULT '0' NOT NULL,
    t3ver_move_id int(11) DEFAULT '0' NOT NULL,
    tstamp int(11) unsigned DEFAULT '0' NOT NULL,
    crdate int(11) unsigned DEFAULT '0' NOT NULL,
    cruser_id int(11) unsigned DEFAULT '0' NOT NULL,
    deleted tinyint(4) unsigned DEFAULT '0' NOT NULL,
    hidden tinyint(4) unsigned DEFAULT '0' NOT NULL,
    starttime tinyint(4) unsigned DEFAULT '0' NOT NULL,
    endtime tinyint(4) unsigned DEFAULT '0' NOT NULL,
    sys_language_uid int(11) DEFAULT '0' NOT NULL,
    l10n_parent int(11) unsigned DEFAULT '0' NOT NULL,
    l10n_diffsource mediumblob,
    tx_swiper_image int(11) unsigned DEFAULT '0' NOT NULL,
    tx_swiper_content int(11) unsigned DEFAULT '0' NOT NULL,
    PRIMARY KEY (uid),
    KEY parent (pid),
    KEY t3ver_oid (t3ver_oid,t3ver_wsid),
    KEY language (l10n_parent,sys_language_uid)
);
